spring:
  datasource:
    url: jdbc:mariadb://192.0.3.43:3306/spring  # ?? ????? ??
    driver-class-name: org.mariadb.jdbc.Driver
    username: osj
    password: qwer1234

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: dhtmdwo73@gmail.com
    password: zjxgmyaudjyjhzvf
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          timeout: 5000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace