spring:
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:mariadb://192.0.3.42:3306/spring  # ?? ????? ??
    driver-class-name: org.mariadb.jdbc.Driver
    username: osj
    password: qwer1234

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: dhtmdwo73@gmail.com
    password: zjxgmyaudjyjhzvf
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          timeout: 5000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret : ${JWT_SECRET}
  expired: ${JWT_EXPIRED}
